[package]
name = "api_hello_world"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
wire_weaver = { path = "../../crates/wire_weaver" }
shrink_wrap = { path = "../../crates/shrink_wrap" }
