[workspace.package]
version = "0.4.0"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
description = "WireWeaver is a wire format and API code generator for resource constrained systems."

[workspace.dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[workspace]
resolver = "2"
members = [
    "crates/*",
    "examples/*",
    "tests"
]

[patch.crates-io]
embassy-usb = { git = "https://github.com/embassy-rs/embassy" }
