[workspace.package]
version = "0.3.0"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
description = ""
documentation = ""

[workspace.dependencies]
anyhow = "1.0"
pest = "2.5"
pest_derive = "2.5"
itertools = "0.10"
codespan-reporting = "0.11"

[workspace]
members = [
    "vhl-core",
    "ast",
    "parser",
    "cli",
    "codegen",
    "mtoken",
    "mquote",
    "vhl-stdlib/vhl-stdlib-rust",
    "vhl-stdlib/xpi-node-rust",
    "vhl-stdlib/xpi-rust",
    "eval",
    "examples/xpi_server"
]