[workspace.package]
version = "0.4.0"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
description = "WireWeaver is a wire format and API code generator for resource constrained systems."

[workspace.dependencies]

[workspace]
resolver = "2"
members = [
    "crates/*",
    "examples/*",
]