[package]
name = "vhl"
version = "0.3.0"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
edition = "2018"
keywords = ["language", "api", "m2m"]
license = "MIT"
description = ""
readme = "README.md"

[lib]
name = "vhl"
path = "src/lib.rs"

[dependencies]
parser = { path = "./parser" }

[workspace]
members = ["parser", "cli", "codegen", "mtoken", "mquote", "vhl-stdlib/vhl-stdlib-rust"]