[package]
name = "cli"
version = "0.2.0"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
edition = "2018"

[dependencies]
vhl = { path = ".." }
parser = { path = "../parser" }
codegen = { path = "../codegen" }

[features]
backtrace = ["parser/backtrace"]