[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
quote = "1.0"
proc-macro2 = "1.0"
mtoken = { path = "../mtoken" }
mquote = { path = "../mquote" }