[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
thiserror = "1.0"
codespan-reporting = "0.11"
ast = { path = "../ast" }

[dev-dependencies]
parser-test = "0.3.3"

[features]
backtrace = []