[package]
name = "xpi-node"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0" }
tokio = { version = "^1.24.1", features = ["full"] }
tokio-stream = { version = "^0.1.9" }
tokio-util = { version = "0.7.4", features = ["codec"] }
bytes = "1.2.1"
futures = { version = "0.3.25" }
tracing = "0.1"
xpi = { path = "../xpi-rust" }
vhl-stdlib = { path = "../vhl-stdlib-rust" }
crc-any = "2.4"

[features]
dynamic = [] # include full vhl vhl_core allowing run time parsing of vhl files, expression evaluation, etc
