[package]
name = "xpi"
version = "0.1.0"
edition = "2021"

[dependencies]
vhl-stdlib = { path = "../vhl-stdlib-rust" }

[dev-dependencies]
hex-literal = "^0.3.4"

[features]
no_std = ["vhl-stdlib/no_std"]