[package]
name = "wire_weaver_usb_embassy"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
embassy-usb = "0.2.0"
embassy-sync = "0.6.0"
defmt = "0.3"