[package]
name = "xpi_server"
version = "0.1.0"
edition = "2021"

[dependencies]
xpi-client-server = { path = "../../vhl-stdlib-rust/xpi-client-server" }
xpi = { path = "../../vhl-stdlib-rust/xpi" }

anyhow = { workspace = true }

tokio = { version = "^1.20.1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
