[package]
name = "ww_codegen"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
quote = { workspace = true }
proc-macro2 = { workspace = true }

ww_ast = { path = "../ww_ast" }
