[package]
name = "xpi-client-server"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0" }
tokio = { version = "^1.24.1", features = ["full"] }
tokio-stream = { version = "^0.1.9" }
# tokio-util = { version = "0.7.4", features = ["codec"] }
bytes = "1.2.1"
futures = { version = "0.3.25" }
futures-util = "0.3"
tracing = "0.1"
xpi = { path = "../xpi" }
vhl-stdlib = { path = "../vhl-stdlib" }
# crc-any = "2.4"
serde = "1"
tokio-tungstenite = "0.19"
rmp-serde = "1.1"

[features]
dynamic = [] # include full vhl vhl_core allowing run time parsing of vhl files, expression evaluation, etc
